@baseUrl = http://localhost:3000/api
@app_route = /norme_study
@ping_route = {{baseUrl}}{{app_route}}/ping
@testUrl = {{baseUrl}}{{app_route}}/

//Ping route
GET {{ping_route}} HTTP/1.1

###
//Get request
GET {{testUrl}}/1 HTTP/1.1

###
//Post request
POST {{testUrl}} HTTP/1.1
content-type: application/json

{
  "nome": "Pojo tester",
  "anni": 10
}

###
//Prova delete
POST {{testUrl}}/d HTTP/1.1
content-type: application/json

{
  "id": 43
}

###
//Update request sostituzione completa
PUT  {{testUrl}} HTTP/1.1
content-type: application/json

{
    "_id": "6069b22433f72304c8a25b50",
    "idMacchina": 4
}

###
//Update request aggiornamento alcuni campi
PATCH   {{testUrl}} HTTP/1.1
content-type: application/json

{
    "_id": "6069b22433f72304c8a25b50",
    "idMacchina": 4
}

###
//Delete request
DELETE   {{testUrl}} HTTP/1.1
content-type: application/json

{
    "_id": "6069b22433f72304c8a25b50"
}