@baseUrl = http://localhost:3000/api
@app_route = /norme_study
@ping_route = {{baseUrl}}{{app_route}}/ping
@testUrl = {{baseUrl}}{{app_route}}/

//Ping route
GET {{ping_route}} HTTP/1.1

###
//Get request
GET {{testUrl}}/ HTTP/1.1

###
//Post request
POST {{testUrl}} HTTP/1.1
content-type: application/json

{
  "nome": "Pojo tester",
  "anni": 10
}

###
//Prova delete
DELETE  {{testUrl}}/ HTTP/1.1
content-type: application/json

{
  "id": 46
}

###
//Prova update
PUT  {{testUrl}}/ HTTP/1.1
content-type: application/json

{
  "id": 46,
  "nome": "Updated pojo model",
  "anni": 10  
}
###
